<?php

/**
 * @file
 * Contains hide_starts_with.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function hide_starts_with_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hide_starts_with module.
    case 'help.page.hide_starts_with':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A Facet API processor that hides all results that start with a configurable character.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function hide_starts_with_theme() {
  $theme = [];

  return $theme;
}
