plugin.plugin_configuration.facets_processor.hide_starts_with:
  type: mapping
  label: 'Settings for the hide-starts-with processor'
  mapping:
    character:
      type: string
      label: Character
